# Generated by Django 3.2.16 on 2022-11-22 02:42

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('start', models.DateTimeField(verbose_name='Event start time')),
                ('end', models.DateTimeField(verbose_name='Event end time')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='trailGuideLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_initial', models.CharField(max_length=5)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='subEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('alternate_leader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alternate_leader_sub_event', to='leaderSignUp.trailguideleader')),
                ('event_parent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leaderSignUp.events')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderSignUp.group')),
                ('primary_leader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leader_sub_event', to='leaderSignUp.trailguideleader')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='alternate_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alternate_leader', to='leaderSignUp.trailguideleader'),
        ),
        migrations.AddField(
            model_name='events',
            name='primary_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leader', to='leaderSignUp.trailguideleader'),
        ),
    ]
