# Generated by Django 3.2.16 on 2022-12-27 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('start', models.DateTimeField(verbose_name='Event start time')),
                ('end', models.DateTimeField(verbose_name='Event end time')),
            ],
        ),
        migrations.CreateModel(
            name='eventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='trailman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True)),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='Trailmen Birthdate')),
            ],
        ),
        migrations.CreateModel(
            name='trailGuideLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailguide', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('alternate_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_leader_sub_event', to='leaderSignUp.trailguideleader')),
                ('event_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderSignUp.event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderSignUp.group')),
                ('primary_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_sub_event', to='leaderSignUp.trailguideleader')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='alternate_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_leader', to='leaderSignUp.trailguideleader'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='leaderSignUp.eventtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='leaderSignUp.trailguideleader'),
        ),
    ]
