# Generated by Django 3.2.16 on 2022-12-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderSignUp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevent',
            name='group',
        ),
        migrations.AddField(
            model_name='subevent',
            name='group',
            field=models.ManyToManyField(to='leaderSignUp.group'),
        ),
    ]
