# Generated by Django 3.2.16 on 2022-11-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderSignUp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='event',
        ),
        migrations.RenameModel(
            old_name='eventCategory',
            new_name='eventType',
        ),
        migrations.RenameModel(
            old_name='subEvents',
            new_name='subEvent',
        ),
    ]
