# Generated by Django 3.2.16 on 2022-11-23 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderSignUp', '0002_auto_20221122_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='leaderSignUp.eventtype'),
        ),
    ]
