# Generated by Django 3.2.16 on 2022-12-29 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderSignUp', '0002_auto_20221228_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevent',
            name='group',
        ),
        migrations.AddField(
            model_name='subevent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderSignUp.group'),
        ),
    ]
