# Generated by Django 3.2.16 on 2022-12-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderSignUp', '0003_event_eventtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevent',
            name='title',
        ),
    ]
