# Generated by Django 3.2.16 on 2022-12-10 20:33

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderSignUp', '0004_remove_subevent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='trailman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_initial', models.CharField(blank=True, max_length=5)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('birth_day', models.DateField(blank=True, verbose_name='Trailmen Birthdate')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='alternate_leader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alternate_leader_sub_event', to='leaderSignUp.trailguideleader'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='primary_leader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='leader_sub_event', to='leaderSignUp.trailguideleader'),
        ),
    ]
