# Generated by Django 3.2.16 on 2023-01-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderSignUp', '0005_auto_20230109_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
