# Generated by Django 3.2.16 on 2022-12-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderSignUp', '0005_auto_20221210_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevent',
            name='alternate_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alternate_leader_sub_event', to='leaderSignUp.trailguideleader'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='primary_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='leader_sub_event', to='leaderSignUp.trailguideleader'),
        ),
    ]
