# Generated by Django 3.2.16 on 2022-12-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderSignUp', '0007_auto_20221210_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
    ]
