# Generated by Django 3.2.16 on 2022-12-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderSignUp', '0008_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='alternate_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alternate_leader', to='leaderSignUp.trailguideleader'),
        ),
        migrations.AlterField(
            model_name='event',
            name='primary_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='leader', to='leaderSignUp.trailguideleader'),
        ),
    ]
